language: python
python: "3.5"

sudo: false

env:
  # TOX_ENV=py35-django21
  # TOX_ENV=py27-django20
  # TOX_ENV=py35-django20
  # TOX_ENV=py34-django20
  # TOX_ENV=py27-django20
  - TOX_ENV=py35-django111
  - TOX_ENV=py34-django111
  - TOX_ENV=py27-django111
  - TOX_ENV=py35-django110
  - TOX_ENV=py34-django110
  - TOX_ENV=py27-django110
  - TOX_ENV=py35-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py27-django19
  - TOX_ENV=py34-django18
  - TOX_ENV=py33-django18
  - TOX_ENV=py27-django18
  - TOX_ENV=py34-django17
  - TOX_ENV=py33-django17
  - TOX_ENV=py27-django17

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
